const moo = require('moo');
const lexer = moo.compile({
    operandSeparator: /[ \t]*,[ \t]*/,
    ws: /[ \t]+/,
    register: { match: /[rR][0-7](?![^ \t])/, value: s => s.toLowerCase() },
    addAndOpcode: { match: /(?:[aA][dD][dD]|[aA][nN][dD])(?![^ \t])/, value: s => s.toLowerCase() },
    brOpcode: { match: /[bB][rR][nN]?[zZ]?[pP]?(?![^ \t])/, value: s => s.toLowerCase() },
    jmpOpcode: { match: /[jJ][mM][pP](?![^ \t])/, value: s => s.toLowerCase() },
    retOpcode: { match: /[rR][eE][tT](?![^ \t])/, value: s => s.toLowerCase() },
    rtiOpcode: { match: /[rR][tT][iI](?![^ \t])/, value: s => s.toLowerCase() },
    jsrrOpcode: { match: /[jJ][sS][rR][rR](?![^ \t])/, value: s => s.toLowerCase() },
    jsrOpcode: { match: /[jJ][sS][rR](?![^ \t])/, value: s => s.toLowerCase() },
    ldrStrOpcode: { match: /(?:[lL][dD][rR]|[sS][tT][rR])(?![^ \t])/, value: s => s.toLowerCase() },
    ldLdiStStiLeaOpcode: { match: /(?:[lL][dD]|[lL][dD][iI]|[sS][tT]|[sS][tT][iI]|[lL][eE][aA])(?![^ \t])/, value: s => s.toLowerCase() },
    notOpcode: { match: /[nN][oO][tT](?![^ \t])/, value: s => s.toLowerCase() },
    trapOpcode: { match: /[tT][rR][aA][pP](?![^ \t])/, value: s => s.toLowerCase() },
    getcOpcode: { match: /[gG][eE][tT][cC](?![^ \t])/, value: s => s.toLowerCase() },
    outOpcode: { match: /[oO][uU][tT](?![^ \t])/, value: s => s.toLowerCase() },
    putsOpcode: { match: /[pP][uU][tT][sS](?![^ \t])/, value: s => s.toLowerCase() },
    inOpcode: { match: /[iI][nN](?![^ \t])/, value: s => s.toLowerCase() },
    putspOpcode: { match: /[pP][uU][tT][sS][pP](?![^ \t])/, value: s => s.toLowerCase() },
    haltOpcode: { match: /[hH][aA][lL][tT](?![^ \t])/, value: s => s.toLowerCase() },
    decimal: /#(?:[+-]?[0-9]+)(?![^ \t])/,
    binary: { match: /0[bB][0-1]+(?![^ \t])/, value: s => s.toLowerCase() },
    hexadecimal: { match: /0[xX][0-9a-fA-F]+(?![^ \t])/, value: s => s.toLowerCase() },
    endDirective: { match: /\.[eE][nN][dD](?![^ \t])/, value: s => s.toLowerCase() },
    origDirective: { match: /\.[oO][rR][iI][gG](?![^ \t])/, value: s => s.toLowerCase() },
    fillDirective: { match: /\.[fF][iI][lL][lL](?![^ \t])/},
    blkwDirective: { match: /\.[bB][lL][kK][wW](?![^ \t])/, value: s => s.toLowerCase() },
    stringzDirective: { match: /\.[sS][tT][rR][iI][nN][gG][zZ](?![^ \t])/, value: s => s.toLowerCase() },
    comment: /;[^\n]*/,
    fillCharacter: /'.*'/,
    stringzSequence: /".*"/,
    label: /[a-zA-Z][a-zA-Z0-9_]*:?/,
    error: /\S+/,
});

module.exports = lexer;